### ISSUE TITLE
Data management system (DMS) API Specification

### ISSUE THREAD

**Issue by Xarthisius** [whole-tale/girder_wt_data_manager#1]

**Comment by hategan** [comment]
The readme documents the API to a large extent, but that might not be what you are looking for. So take a look and let me know.

**Comment by Xarthisius** [comment]
README in connection with gdocs document is fine. At some point it would be nice to have it directly in the code using girder's native support for swagger, but it's not necessary right now.

**Comment by hategan** [comment]
Resources already have swagger annotations, but they do not necessarily provide the big picture.
