### ISSUE TITLE
Unable to access child items in a session that was created with a single root directory

### ISSUE THREAD

**Issue by Xarthisius** [whole-tale/girder_wt_data_manager#21]
Steps to reproduce:
1. Create a folder with a subfolder and an item (I registered doi: `10.5065/D6862DM8` from DataONE)
2. Create a session using `[{'itemId' : 'id_of_root_folder', 'mountPath': '/'}]`
3. Mount `wt_dms` using [girderfs](https://github.com/whole-tale/girderfs) and newly created session
4. Try reading bytes from any file via `cat`/`head`

Result:
```head: cannot open 'datadict2005.html' for reading: Bad address```
which is caused by 404 exception raised in https://github.com/whole-tale/girder_wt_data_manager/blob/master/server/resources/lock.py#L99

Expected results:
Bytes

Notes:
Works flawlessly with https://github.com/whole-tale/girder_wt_data_manager/commit/310020359b47355edd298481e169e23501cfcdf0

**Comment by hategan** [comment]
I know what I did wrong there...

**Comment by Xarthisius** [comment]
... not issuing a pull request before introducing a new feature? ;)

**Comment by hategan** [comment]
Broken code is broken code no matter where it lives

**Comment by Xarthisius** [comment]
No longer an issue
