### ISSUE TITLE
Maybe disable email notifications

### ISSUE THREAD

**Issue by hategan** [whole-tale/girder_wt_data_manager#28]
Globus sends emails on completed/failed/etc. transfers. This may be fine when you transfer large things sporadically, but doubtfully so when using Globus in an automated fashion. I think the user can disable notifications in general somewhere on the Globus site, but I could not find it. The API supports disabling notifications for each request. We should probably use that.

**Comment by Xarthisius** [comment]
That's a really good idea, since we're using separate transfers for individual files.
