### ISSUE TITLE
Add lazy checksum/hash checking

### ISSUE THREAD

**Issue by hategan** [whole-tale/girder_wt_data_manager#50]
There are cases, such as for example bags, when checksums are specified for files. Validating files against these checksums is a prudent move from a reproducible science perspective. However, downloading all data when registering it is quite contrary to the architecture we have and the point of the DMS.

Point being, we should implement lazy validation that:
1. stores checksums in the metadata for DMS files
2. verifies checksums whenever the DMS caches a file with a checksum stored in (1)

**Comment by Xarthisius** [comment]
Fixed by https://github.com/whole-tale/girder_wt_data_manager/pull/53
