### ISSUE TITLE
DMS implementation (externally to containers)

### ISSUE THREAD

**Issue by hategan** [whole-tale/girder_wt_data_manager#7]

**Comment by hategan** [comment]
What was this again and does the current code fit the bill?

**Comment by Xarthisius** [comment]
AFAIR it was meant to describe what you've been doing so far, i.e. everything related to DMS on girder side in contrast to actually using DMS withing fuse filesystem and containers.

**Comment by hategan** [comment]
That was my feel too. In a sense, it seems like one of those eternally open issues (aka. "Issue #119: 'write code'"). I'll keep it open for now since the GC stuff, which is generic, and an essential part, needs testing before it can be called functioning.

**Comment by hategan** [comment]
GC seems to be functioning and is part of the tests
