### ISSUE TITLE
Integration between existing EFS and DMS

### ISSUE THREAD

**Issue by hategan** [whole-tale/girder_wt_data_manager#8]

**Comment by hategan** [comment]
@Xarthisius We should sync about how we want to go about this. Roughly, the FUSE client should lock items and wait for them to be cached using the DM API.

**Comment by Xarthisius** [comment]
Yeah, we do. I haven't had time fully grok your code yet. I'll try to do it today.

**Comment by hategan** [comment]
The rough idea is in efs.py.

**Comment by hategan** [comment]
There is a 'dms' branch in griderfs that implements this. It requires b28ba36
